package com.fm.trans.domain;

// Generated Dec 13, 2012 4:09:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	private String username;
	private Set<Items> itemses = new HashSet<Items>(0);

	public User() {
	}

	public User(String username) {
		this.username = username;
	}

	public User(String username, Set<Items> itemses) {
		this.username = username;
		this.itemses = itemses;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 200)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

}
